name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - main
env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create build
        working-directory: ./patientmonitor
        run: npm --force install && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PATIENTMONITORINTERFACE }}'
          channelId: live
          projectId: patientmonitorinterface
          entryPoint: ./patientmonitor